"""init

Revision ID: 68bb1892f945
Revises:
Create Date: 2022-07-10 01:32:49.526316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68bb1892f945'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'apps',
        sa.Column('id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.Column('android_package_name',
                  sa.String(), nullable=True),
        sa.UniqueConstraint('android_package_name'),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('category', postgresql.ENUM(
            'GAME', 'OTHER', name='category'), nullable=False),
        sa.Column('android_category', sa.String(), nullable=True),
        sa.Column('icon_preview', sa.String(), nullable=True),
        sa.Column('image_wide', sa.String(), nullable=True),
        sa.Column('icon_large', sa.String(), nullable=True),
    )
    op.create_index(op.f('ix_apps_id'), 'apps', ['id'], unique=True)
    op.create_table(
        'users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('nickname', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('firebase_messaging_token',
                  sa.String(), nullable=True),
        sa.Column('profile_pic', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users',
                    ['nickname'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table(
        'user_in_app_statistics',
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('app_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'app_id')
    )
    op.create_table(
        'user_statuses',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('current_app_id', sa.String(), nullable=True),
        sa.Column('last_update', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('finished', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['current_app_id'], ['apps.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_statuses_id'),
                    'user_statuses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_statuses_id'), table_name='user_statuses')
    op.drop_table('user_statuses')
    op.drop_table('user_in_app_statistics')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_apps_id'), table_name='apps')
    op.drop_table('apps')
    # ### end Alembic commands ###
