"""user_in_app_records

Revision ID: 75374367cdb3
Revises: ada1332b86e7
Create Date: 2022-11-15 14:05:51.412914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75374367cdb3'
down_revision = 'ada1332b86e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_in_app_records',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('app_id', sa.String(), nullable=True),
        sa.Column('dt_begin', sa.DateTime(), nullable=False),
        sa.Column('dt_end', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_in_app_records_dt_end'),
                    'user_in_app_records', ['dt_end'], unique=False)
    op.add_column('user_in_app_statistics', sa.Column(
        'installed', sa.Boolean(), nullable=False))
    op.add_column('user_in_app_statistics', sa.Column(
        'dt_stats_updated_at', sa.DateTime(), nullable=True))
    op.add_column('user_in_app_statistics', sa.Column(
        'activity_last_two_weeks', sa.Interval(), server_default='0', nullable=False))
    op.add_column('user_in_app_statistics', sa.Column(
        'activity_total', sa.Interval(), server_default='0', nullable=False))
    op.add_column('user_in_app_statistics', sa.Column(
        'dt_last_acivity', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_in_app_statistics', 'dt_last_acivity')
    op.drop_column('user_in_app_statistics', 'activity_total')
    op.drop_column('user_in_app_statistics', 'activity_last_two_weeks')
    op.drop_column('user_in_app_statistics', 'dt_stats_updated_at')
    op.drop_column('user_in_app_statistics', 'installed')
    op.drop_index(op.f('ix_user_in_app_records_dt_end'),
                  table_name='user_in_app_records')
    op.drop_table('user_in_app_records')
    # ### end Alembic commands ###
