"""do not disturbe

Revision ID: a88ad21d28bd
Revises: 5c486b435974
Create Date: 2022-07-20 11:05:58.926163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88ad21d28bd'
down_revision = '5c486b435974'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'do_not_disturbe_mode',
        sa.Boolean(),
        nullable=False,
        server_default="FALSE",
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'do_not_disturbe_mode')
    # ### end Alembic commands ###
