"""fix acivity

Revision ID: f6c58a860367
Revises: 75374367cdb3
Create Date: 2023-01-29 14:10:13.233180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6c58a860367'
down_revision = '75374367cdb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apps', 'category',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=False)
    op.add_column('user_in_app_statistics', sa.Column(
        'dt_last_activity', sa.DateTime(), nullable=True))
    op.drop_column('user_in_app_statistics', 'dt_last_acivity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_in_app_statistics', sa.Column(
        'dt_last_acivity', postgresql.TIMESTAMP(),
        autoincrement=False, nullable=True))
    op.drop_column('user_in_app_statistics', 'dt_last_activity')
    op.alter_column('apps', 'category',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    # ### end Alembic commands ###
