version: '3'

volumes:
  postgres_data: { }
  ch_data: { }

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      dockerfile: Dockerfile
      context: "."
    ports:
      - "8080:8080"
    env_file:
      .env
    depends_on:
      - postgres
