version: '3'

volumes:
  postgres_data: { }
  ch_data: { }

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      .env
    ports:
      - "5432:5432"
