- name: Gathering facts
  hosts: all
  gather_facts: true

- hosts: api
  tasks:
    # - name: Login to Docker Hub
    #   community.docker.docker_login:
    #     username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    #     password: "{{ lookup('env', 'DOCKERHUB_TOKEN') }}"
    - name: Run server
      community.docker.docker_compose:
        project_name: nux server api
        definition:
          services:
            app:
              image: "i3cheese/nux:latest"
              restart: always
              ports:
                - "80:8080"
              environment:
                NUX_PORT: "8080"
                POSTGRES_HOST: "{{POSTGRES_HOST}}"
                POSTGRES_USER: "{{POSTGRES_USER}}"
                POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
                POSTGRES_DB: "{{POSTGRES_DB}}"
                AWS_SECRET_ACCESS_KEY: "{{AWS_SECRET_ACCESS_KEY}}"
                AWS_ACCESS_KEY_ID: "{{AWS_ACCESS_KEY_ID}}"
                NUX_SECRET_KEY: "{{NUX_SECRET_KEY}}"
                GOOGLE_CREDS: "{{GOOGLE_CREDS}}"
                SMSAERO_EMAIL: "{{SMSAERO_EMAIL}}"
                SMSAERO_APIKEY: "{{SMSAERO_APIKEY}}"
        pull: yes
      register: output

