name: Lint the code, run tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  release:
    types: [published, edited]

jobs:
  # Run code tests before building the image, to ensure it is good to go
  lint_and_test:
    name: Run code tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: web
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Setting up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl -sSL 'https://install.python-poetry.org' | python
        poetry install
    - name: Run pytest
      run: |
        poetry run pytest
      env:
        # dont actualy used
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: web
        POSTGRES_HOST: "localhost:5432"
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
    - name: Lint the code with pycodestyle
      run: |
        poetry run flake8 nux --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run pycodestyle nux tests
