name: Lint the code, run tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  release:
    types: [published, edited]

jobs:
  # Run code tests before building the image, to ensure it is good to go
  lint_and_test:
    name: Run code tests
    runs-on: ubuntu-latest
    container: python:3.10.4-slim-buster
    strategy:
      matrix:
        python-version: ["3.10"] # Using a list so it's extensible for future use

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: web
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get install --no-install-recommends -y curl
        curl -sSL 'https://install.python-poetry.org' | python
        poetry install
    - name: Lint the code with pycodestyle
      run: |
        poetry run flake8 nux --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run pycodestyle nux
    - name: Run pytest
      run: |
        pytest
      env:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: web
        POSTGRES_HOST: postgres
