name: Lint the code, run tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  release:
    types: [published, edited]

jobs:
  # Run code tests before building the image, to ensure it is good to go
  build:
    name: Run code tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] # Using a list so it's extensible for future use

    steps:
    - uses: actions/checkout@v3
    - name: Setting up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl -sSL 'https://install.python-poetry.org' | python
        poetry install
    - name: Lint the code with pycodestyle
      run: |
        poetry run flake8 nux --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run pycodestyle nux
